### PR TITLE
Convert to noarch package

### PR DESCRIPTION
**Pull request by mattkram**
The current package recipe brings in a platform-specific dependency on `python_abi`. This can cause some issues with dependency resolution when many other packages are included in the solve.

However, since this library is a simple Python package, we can build a python noarch package instead, which resolves these issues for us.

This PR converts the package from a platform-specific binary package to a noarch python package.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by mattkram** [comment]
@conda-forge-admin, please rerender

**Comment by zaneselvans** [comment]
I'm trying to install this package using micromamba in a docker container doing development on an M1 Mac and running into an error because it's not available for the `linux-aarch64` platform... which I imagine this switch to being a `noarch` package would fix...

@mtekman or @bgruening would you be up for merging it in?

**Review by mtekman — COMMENTED** [review]
So this effectively removes the win and osx targets, and replaces them with linux, which is no longer python version dependent?

**Comment by mattkram** [comment]
> So this effectively removes the win and osx targets, and replaces them with linux, which is no longer python version dependent?

This removes the OS-specific targets and replaces it with an OS/architecture-independent noarch package. This would get built on the Linux runners.

The python version can be specified via a normal pin if needed (e.g. `python >=3.8`), but this will drop the `python_abi` subdependency.

I have a noarch build that can be tried if interested: `conda install -c anaconda-cloud simpleeval`

https://anaconda.org/anaconda-cloud/simpleeval/files

**Review by mtekman — APPROVED** [review]

**Comment by mattkram** [comment]
@conda-forge-admin, please rerender

**Comment by mattkram** [comment]
@mtekman thanks for the review! I've just merged in the latest `main` branch and re-rendered the feedstocks. Should be good to go now once you're happy w/ it.

**Comment by mtekman** [comment]
Nice, thanks for the upgrade!

**Pull request merged**
